// src/service-worker.js

// Import the precacheAndRoute method of Workbox
import { precacheAndRoute } from 'workbox-precaching';

// Use precacheAndRoute to handle __WB_MANIFEST injected by the Workbox plugin
// __WB_MANIFEST is a resource list automatically generated by Workbox during the build process
precacheAndRoute(self.__WB_MANIFEST);

// Handle events during the installation phase and cache other resources
self.addEventListener('install', (event) => {
  console.log('Service Worker installing.');
  self.skipWaiting(); // Skip waiting and activate the new Service Worker immediately
});

// Handle events in the activation phase and clear the old cache
self.addEventListener('activate', (event) => {
  console.log('Service Worker activating.');
// Get all currently cached keys
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
        // Delete caches that are no longer in use
          if (cacheName !== 'my-site-cache-v1') {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
  self.clients.claim(); //Control all clients
});

// Intercept fetch requests and use cache-first strategy
self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      // If a matching response is found in the cache, use the cached content
      if (response) {
        return response;
      }
      // If there is no matching response, make a network request
      return fetch(event.request).then((networkResponse) => {
        //Cache the response obtained from the network
        return caches.open('my-site-cache-v1').then((cache) => {
          cache.put(event.request, networkResponse.clone());
          return networkResponse;
        });
      });
    }).catch(() => {
      // If the network request fails (for example, offline), you can return to a default offline page
      return caches.match('/offline.html');
    })
  );
});
